/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laptrinhcity.giaodien;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import laptrinhcity.DAO.NhanVienDAO;
import laptrinhcity.entity.NhanVien;
import laptrinhcity.utils.Auth;
import laptrinhcity.utils.MsgBox;

/**
 *
 * @author SuongNguyen
 */
public class QuanLyNhanVien1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuanLyNhanVien1
     */
    

    public QuanLyNhanVien1(int i) {
        initComponents();
        setLocation(185, 20);
        tabs.setSelectedIndex(i);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblQuanLyNguoiHoc = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnlCapNhat = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        pnlNutBam = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        pnlDiChuyen = new javax.swing.JPanel();
        btnDau = new javax.swing.JButton();
        btnLui = new javax.swing.JButton();
        btnTien = new javax.swing.JButton();
        btnCuoi = new javax.swing.JButton();
        txtHoTen = new javax.swing.JTextField();
        lblHoTen1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdoTp = new javax.swing.JRadioButton();
        rdoNv = new javax.swing.JRadioButton();
        txtMatKhau = new javax.swing.JTextField();
        pnlDanhSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        setClosable(true);

        lblQuanLyNguoiHoc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQuanLyNguoiHoc.setForeground(new java.awt.Color(255, 0, 0));
        lblQuanLyNguoiHoc.setText("QUẢN LÝ NHÂN VIÊN QUẢN TRỊ");

        lblMaNhanVien.setText("Mã nhân viên");

        lblHoTen.setText("Mật khẩu");

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        pnlNutBam.setLayout(flowLayout1);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlNutBam.add(btnThem);

        btnSua.setText("Sửa");
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlNutBam.add(btnSua);

        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlNutBam.add(btnXoa);

        btnLamMoi.setText("Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlNutBam.add(btnLamMoi);

        pnlDiChuyen.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnDau.setText("|<");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });
        pnlDiChuyen.add(btnDau);

        btnLui.setText("<<");
        btnLui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuiActionPerformed(evt);
            }
        });
        pnlDiChuyen.add(btnLui);

        btnTien.setText(">>");
        btnTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTienActionPerformed(evt);
            }
        });
        pnlDiChuyen.add(btnTien);

        btnCuoi.setText(">|");
        btnCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiActionPerformed(evt);
            }
        });
        pnlDiChuyen.add(btnCuoi);

        lblHoTen1.setText("Họ tên");

        jLabel1.setText("Vai trò");

        buttonGroup1.add(rdoTp);
        rdoTp.setSelected(true);
        rdoTp.setText("Trưởng phòng");

        buttonGroup1.add(rdoNv);
        rdoNv.setText("Nhân viên");

        javax.swing.GroupLayout pnlCapNhatLayout = new javax.swing.GroupLayout(pnlCapNhat);
        pnlCapNhat.setLayout(pnlCapNhatLayout);
        pnlCapNhatLayout.setHorizontalGroup(
            pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoTen)
                    .addComponent(txtMaNhanVien)
                    .addGroup(pnlCapNhatLayout.createSequentialGroup()
                        .addComponent(pnlNutBam, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDiChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCapNhatLayout.createSequentialGroup()
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                .addComponent(rdoTp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoNv))
                            .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoTen)
                            .addComponent(lblHoTen1)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtMatKhau))
                .addContainerGap())
        );
        pnlCapNhatLayout.setVerticalGroup(
            pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHoTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblHoTen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTp)
                    .addComponent(rdoNv))
                .addGap(19, 19, 19)
                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDiChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlNutBam, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlCapNhatLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtHoTen, txtMaNhanVien, txtMatKhau});

        tabs.addTab("Cập nhật", pnlCapNhat);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NH", "Mật khẩu", "Họ tên", "Vai trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        javax.swing.GroupLayout pnlDanhSachLayout = new javax.swing.GroupLayout(pnlDanhSach);
        pnlDanhSach.setLayout(pnlDanhSachLayout);
        pnlDanhSachLayout.setHorizontalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDanhSachLayout.setVerticalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Danh sách", pnlDanhSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabs)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblQuanLyNguoiHoc)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblQuanLyNguoiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        changeEnable(false);
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        if (evt.getClickCount() == 2) {
            index = tblNhanVien.getSelectedRow();
            edit();
            changeEnable(true);
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        first();
    }//GEN-LAST:event_btnDauActionPerformed

    private void btnLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuiActionPerformed
        previous();
    }//GEN-LAST:event_btnLuiActionPerformed

    private void btnTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienActionPerformed
        next();
    }//GEN-LAST:event_btnTienActionPerformed

    private void btnCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiActionPerformed
        last();
    }//GEN-LAST:event_btnCuoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuoi;
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLui;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTien;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblQuanLyNguoiHoc;
    private javax.swing.JPanel pnlCapNhat;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JPanel pnlDiChuyen;
    private javax.swing.JPanel pnlNutBam;
    private javax.swing.JRadioButton rdoNv;
    private javax.swing.JRadioButton rdoTp;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMatKhau;
    // End of variables declaration//GEN-END:variables

    private NhanVienDAO nvD = new NhanVienDAO();
    private int index;
    private     DefaultTableModel tableModel;
    public void init() {
        index = -1;
        tableModel = (DefaultTableModel) tblNhanVien.getModel();
        fillTable();
    }

    private void fillTable() {
        tableModel.setNumRows(0);
        List<NhanVien> nhanVienList = new NhanVienDAO().selectAll();

        nhanVienList.forEach((x) -> {
            String vaiTro = x.isVaiTro() ? "Trưởng phòng" : "Nhân Viên";
            tableModel.addRow(new Object[]{
                x.getMaNhanVien(), x.getMatKhau(), x.getHoTen(), vaiTro
            });
        });
    }

    public void setForm(NhanVien x) {
        txtMaNhanVien.setText(x.getMaNhanVien());
        txtMatKhau.setText(x.getMatKhau());
        txtHoTen.setText(x.getHoTen());
        rdoTp.setSelected(x.isVaiTro());
        rdoNv.setSelected(!x.isVaiTro());
    }
    
    public NhanVien getForm() {
        String maNhanVien = txtMaNhanVien.getText();
        String matKhau = txtMatKhau.getText();
        String hoTen = txtHoTen.getText();
        boolean vaiTro = rdoTp.isSelected();

        return new NhanVien(maNhanVien, matKhau, hoTen, vaiTro);
    }
    
    private void clearForm() {
        NhanVien nv = new NhanVien();
        this.setForm(nv);
    }
    
    public void edit() {
        String maNhanVien = (String) tblNhanVien.getValueAt(index, 0);
        NhanVien nhanvien = nvD.selectById(maNhanVien);
        this.setForm(nhanvien);
        tblNhanVien.setRowSelectionInterval(index, index);
        tabs.setSelectedIndex(0);
    }

   

    private void insert() {
        try {
            
            if (isError()) {
                return;
            }

            nvD.insert(getForm());
            fillTable();
            MsgBox.alert(this, "Thêm thành công");
            changeEnable(true);
        } catch (Exception e) {
            MsgBox.alert(this, e.getMessage());
        }
    }

    private void update() {
        try {
            if (isError()) {
                return;
            }

            nvD.update(getForm());
            fillTable();
            MsgBox.alert(this, "Cập nhật thành công");
            
        } catch (Exception e) {
            MsgBox.alert(this, e.getMessage());
        }
    }

    private void delete() {
        try {
            
            if (isYourself()) {
                MsgBox.alert(this, "Bạn không được xóa chính bạn!");
                return;
            }
            
            if (MsgBox.confirm(this, "Bạn có chắc chắn không?")) {
                nvD.delete(txtMaNhanVien.getText());
                MsgBox.alert(this, "Xóa thành công!");
                fillTable();
                changeEnable(false);
            }
        } catch (Exception e) {
            MsgBox.alert(this, e.getMessage());
        }
    }
    
     public void first() {
        index = 0;
        edit();
    }

    public void previous() {
        index--;
        if (index < 0) {
            index = tblNhanVien.getRowCount() - 1;
        }
        edit();
    }

    public void next() {
        index++;
        if (index > tblNhanVien.getRowCount() - 1) {
            index = 0;
        }
        edit();
    }

    public void last() {
        index = tblNhanVien.getRowCount() - 1;
        edit();
    }

    public boolean isError() {
        if (isEmpty()) {
            MsgBox.alert(this, "Thông tin không được trống!");
            return true;
        }
        if (isPasswordLowerThan(8)) {
            MsgBox.alert(this, "Mật khẩu phải lớn hơn 8 ký tự");
            return true;
        }
        return false;
    }

    public boolean isEmpty() {
        if (txtHoTen.getText().length() == 0
                || txtMaNhanVien.getText().length() == 0) {
            return true;
        }

        return false;
    }

    public boolean isPasswordLowerThan(int i) {
        if (txtMatKhau.getText().length() < i) {
            return true;
        }
        return false;
    }

    

    public boolean isYourself() {
        if (Auth.user.getMaNhanVien().equals(txtMaNhanVien.getText())) {
            return true;
        }
        return false;
    }

    private void changeEnable(boolean b) {
        btnThem.setEnabled(!b);
        btnSua.setEnabled(b);
        btnXoa.setEnabled(b);
        txtMaNhanVien.setEnabled(!b);
    }

}
